[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sahilkhanyousufzai", email = "ahmad.sahel.yousufzai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faker>=40.39.0",
    "fastapi>=0.141.1",
    "google>=3.0.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
